name: pranshal_cms
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  http: ^1.2.2
  sqlite3: ^2.5.0
  json_annotation: ^4.9.0 
  build_runner: ^2.4.14
  crypto: ^3.0.6
  jwt_decoder: ^2.0.1
  uuid: ^4.5.1
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^2.14.2
  mysql1: ^0.20.0
  mailer: ^6.3.0
  shelf_multipart: ^2.0.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
